on:
  push:
    branches:
      - main
      
jobs:
  run-playbooks:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Run Ansible Playbook
      run: ansible-playbook -i inventory/hosts update.yml
  
      
